version: '3.9'

services:
  reactnative:
    build:
      context: .
      dockerfile: dockerfile.reactnative
    volumes:
      - .:/app
      - /app/node_modules
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=development
      - ANDROID_SDK_ROOT=/usr/local/android-sdk
    privileged: true
    container_name: tr_rn
    devices:
      - /dev/bus/usb:/dev/bus/usb